baseURL = 'https://zerozeroseix.github.io/o-meu-sitio-hugo/'
languageCode = 'gl'
title = 'Brand'
theme = "tale"

[Author]
name = "Zeroseroseix"


[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "Contacto"
    title = "Contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0

[params]
  css = ["css/estilos.css"]